import {COLORS, SCREEN, SCREEN_PADDING} from '../../../constants';
import {SharedStyles} from '../../../shared';

const {StyleSheet} = require('react-native');

const styles = StyleSheet.create({
  compareContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    position: 'absolute',
    borderRadius: 300,
    bottom: 30,
    right: SCREEN_PADDING,
  },
  compareText: {
    marginLeft: 5,
    marginTop: -1,
  },
  compareSelected: {
    backgroundColor: COLORS.PRIMARY_LIGHT,
  },
  compareDefault: {
    backgroundColor: COLORS.WHITE,
  },
  carouselImageBg: {
    width: '100%',
    height: '100%',
  },
  overlayTopRow: {
    position: 'absolute',
    left: 0,
    top: 0,
    paddingHorizontal: SCREEN_PADDING,
    flexDirection: 'row',
  },
  headerCircleBtn: {
    height: 44,
    width: 44,
    borderRadius: 22,
    backgroundColor: COLORS.WHITE,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerCircleBtnSpacing: {
    marginLeft: 12,
  },
  rightHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    justifyContent: 'flex-end',
  },
  dotsContainer: {
    position: 'absolute',
    bottom: 38,
    width: '100%',
    alignItems: 'center',
  },
  dotsRow: {
    flexDirection: 'row',
  },
  dotBase: {
    height: 8,
    width: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  dotActive: {
    backgroundColor: COLORS.PRIMARY,
  },
  dotInactive: {
    backgroundColor: COLORS.GREYSCALE_200,
  },
  scrollContentContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SCREEN_PADDING,
    paddingTop: 24,
    paddingBottom: 120,
  },
  scrollBase: {
    position: 'absolute',
    width: '100%',
  },
  contentSheet: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: SCREEN_PADDING,
    paddingTop: 24,
    paddingBottom: 120,
    marginTop: -20,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedPillWrap: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: COLORS.PRIMARY_20,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 100,
    marginLeft: 10,
  },
  verifiedIcon: {
    height: 20,
    width: 20,
    borderRadius: 10,
    backgroundColor: COLORS.PRIMARY,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 4,
  },
  subLocationSpacing: {
    marginVertical: 4,
  },
  tabsContainer: {
    paddingVertical: 20,
  },
  tabChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 100,
    marginRight: 10,
    backgroundColor: COLORS.GREYSCALE_50,
  },
  tabChipSelected: {
    backgroundColor: COLORS.PRIMARY,
  },
  paragraphSpacing: {
    marginTop: 4,
  },
  ownershipCard: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ownershipIcon: {
    height: 24,
    width: 24,
    borderRadius: 6,
    backgroundColor: COLORS.PRIMARY,
    marginRight: 10,
  },
  ownershipTexts: {
    flex: 1,
  },
  featuresRow: {
    flexDirection: 'row',
    marginTop: 16,
  },
  featureCard: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    // padding: 12,
    alignItems: 'center',
    marginRight: 10,
    paddingBottom: 8,
    paddingTop: 12,
  },
  featureIcon: {
    height: 28,
    width: 28,
    borderRadius: 6,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  featureLabel: {
    marginTop: 8,
  },
  sectionHeaderRow: {
    marginTop: 10,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  amenitiesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -6,
    marginBottom: 4,
  },
  amenityCard: {
    width: '25%',
    paddingHorizontal: 6,
    marginBottom: 14,
    alignItems: 'center',
    // paddingVertical: 10,
  },
  amenityIcon: {
    height: 52,
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  amenityText: {
    marginTop: 6,
    textAlign: 'center',
  },
  sectionSpacing: {
    // marginTop: 8,
    marginBottom: 16,
  },
  ownershipWrapper: {
    backgroundColor: COLORS.PRIMARY_20,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 16,
    marginTop: 14,
  },
  ownershipTitleSpacing: {
    marginLeft: 10,
  },
  developerCard: {
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  flex1: {
    flex: 1,
  },
  developerLogo: {
    height: 44,
    width: 44,
    borderRadius: 22,
    marginRight: 10,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  mapImage: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  mapWrap: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: COLORS.GREYSCALE_100,
    marginBottom: 12,
  },
  mapSmall: {
    flex: 1,
  },
  footerCta: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: SCREEN_PADDING,
    backgroundColor: COLORS.WHITE,
    paddingVertical: 20,
    ...SharedStyles.shadow,
  },
  // Payments & Installments
  planCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 14,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    // marginTop: 16,
    ...SharedStyles.shadow,
  },
  planHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  planHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  planPill: {
    backgroundColor: COLORS.PRIMARY_30,
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  planPriceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    // marginTop: 6,
  },
  planPerText: {
    marginLeft: 6,
    marginBottom: 2,
  },
  planArrowRight: {
    marginLeft: 'auto',
  },
  planTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 8,
    marginTop: 10,
  },
  planTag: {
    borderRadius: 8,
    backgroundColor: COLORS.GREYSCALE_50,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  financeCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 14,
    padding: 16,
    marginTop: 6,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    ...SharedStyles.shadow,
  },
  financeTitle: {
    marginBottom: 10,
  },
  financeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sliderRail: {
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.GREYSCALE_200,
    overflow: 'hidden',
  },
  sliderFill: {
    height: '100%',
    backgroundColor: COLORS.PRIMARY,
  },
  sliderThumb: {
    position: 'absolute',
    top: -6,
    height: 20,
    width: 20,
    borderRadius: 10,
    backgroundColor: COLORS.WHITE,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY,
    transform: [{translateX: -10}],
  },
  sliderQuarterFill: {
    width: '25%',
  },
  sliderQuarterThumb: {
    left: '25%',
  },
  // Sticky Range Slider custom parts
  rsThumb: {
    height: 15,
    width: 15,
    borderRadius: 11,
    backgroundColor: COLORS.PRIMARY,
    borderWidth: 2,
    borderColor: COLORS.PRIMARY,
  },
  rsRail: {
    height: 8,
    borderRadius: 4,
    backgroundColor: 'rgba(229, 231, 235, 1)',
    width: SCREEN.WIDTH - SCREEN_PADDING * 4 - 10,
  },
  rsRailSelected: {
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.PRIMARY,
  },
  rsNotch: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COLORS.PRIMARY,
  },
  planDurationLabel: {
    marginTop: 16,
    marginBottom: 8,
  },
  dropdownInput: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    paddingHorizontal: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  chevronDown: {
    transform: [{rotate: '90deg'}],
  },
  monthlySummary: {
    marginTop: 12,
    backgroundColor: COLORS.PRIMARY_30,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  noteCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    backgroundColor: COLORS.GREYSCALE_50,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  noteIcon: {
    height: 24,
    width: 24,
    borderRadius: 12,
    backgroundColor: COLORS.PRIMARY_30,
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noteText: {
    flex: 1,
  },
  // Documents
  docSectionTitle: {
    // marginTop: 10,
    marginBottom: 16,
  },
  docRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
  },
  docLeftIcon: {
    height: 40,
    width: 40,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY_30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  docVerifiedPill: {
    marginTop: 6,
    alignSelf: 'flex-start',
    backgroundColor: COLORS.PRIMARY_20,
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  docRightIcon: {
    height: 36,
    width: 36,
    borderRadius: 18,
    backgroundColor: COLORS.PRIMARY_30,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  // Area Insights
  aiSectionTitle: {
    marginBottom: 8,
    // marginTop: 4,
  },
  aiRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
  },
  aiLeftIcon: {
    height: 40,
    width: 40,
    borderRadius: 8,
    backgroundColor: COLORS.PRIMARY_30,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  aiChipRow: {
    flexDirection: 'row',
    columnGap: 8,
    marginTop: 6,
  },
  aiChip: {
    borderRadius: 100,
    backgroundColor: COLORS.GREYSCALE_50,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  aiRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 6,
    marginTop: 6,
  },
  aiRatingText: {
    marginLeft: 2,
  },
  aiExploreBtnWrap: {
    marginTop: 12,
    marginBottom: 8,
  },
  // Construction Updates
  cuCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    ...SharedStyles.shadow,
  },
  cuCardTitle: {
    marginBottom: 10,
  },
  cuProgressRail: {
    height: 10,
    borderRadius: 6,
    backgroundColor: COLORS.GREYSCALE_200,
    overflow: 'hidden',
  },
  cuProgressFill: {
    height: '100%',
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 6,
  },
  cuProgress75: {
    width: '75%',
  },
  cuPillsRow: {
    flexDirection: 'row',
    columnGap: 8,
    marginTop: 10,
    alignItems: 'center',
  },
  cuPillPrimary: {
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  cuPillOutline: {
    backgroundColor: COLORS.PRIMARY_20,
    borderRadius: 100,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  cuSectionLabel: {
    marginTop: 8,
    marginBottom: 16,
  },
  cuTimelineCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    padding: 10,
    marginBottom: 10,
    backgroundColor: COLORS.WHITE,
  },
  cuTimelineThumb: {
    height: 64,
    width: 64,
    borderRadius: 8,
    marginRight: 10,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  cuTimelineHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    // marginBottom: 4,
  },
  cuOnTrackPill: {
    backgroundColor: COLORS.PRIMARY_30,
    borderRadius: 100,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  cuMoreLink: {
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 6,
  },
  cuGalleryRow: {
    flexDirection: 'row',
    columnGap: 10,
  },
  cuGalleryImage: {
    height: 64,
    width: 64,
    borderRadius: 8,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  cuGalleryLargeRow: {
    flexDirection: 'row',
    columnGap: 14,
  },
  cuGalleryLargeImage: {
    height: 109,
    width: (SCREEN.WIDTH - SCREEN_PADDING * 2 - 14 * 2) / 3,
    borderRadius: 8,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  cuGalleryThirdWrap: {
    position: 'relative',
  },
  cuGalleryOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.25)',
    borderRadius: 24,
  },
  cuGalleryScroll: {
    columnGap: 14,
  },
  cuGalleryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 14,
    rowGap: 14,
  },
  cuGalleryGridImage: {
    height: 109,
    width: (SCREEN.WIDTH - SCREEN_PADDING * 2 - 14 * 2) / 3,
    borderRadius: 8,
    backgroundColor: COLORS.GREYSCALE_100,
  },
  mapTitleSpacing: {
    marginVertical: 16,
  },
  ownershipOptionsCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    ...SharedStyles.shadow,
  },
  ownershipOptionsTitle: {
    marginBottom: 8,
  },
  ownershipOptionsPrice: {
    marginBottom: 12,
  },
  ownershipOptionsTagsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 8,
    marginBottom: 16,
  },
  ownershipOptionsTag: {
    borderRadius: 100,
    backgroundColor: COLORS.GREYSCALE_50,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ownershipRoiBox: {
    backgroundColor: COLORS.PRIMARY_20,
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  ownershipRoiText: {
    marginLeft: 10,
  },
  ownershipRoiCard: {
    backgroundColor: COLORS.PRIMARY_30,
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ownershipRoiValue: {
    marginTop: 4,
  },
  viewFullFinancingBtn: {
    marginTop: 16,
    marginBottom: 8,
  },
  aiMoreLink: {
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 16,
  },
  docGroupContainer: {
    marginBottom: 24,
  },
});

export default styles;
