import {StyleSheet} from 'react-native';
import {COLORS, FONTS, SCREEN, SCREEN_PADDING} from '../../../constants';
import {SharedStyles} from '../../../shared';

const styles = StyleSheet.create({
  rightComponent: {
    position: 'absolute',
    borderWidth: 1,
    height: 44,
    width: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: COLORS.GREYSCALE_200,
    backgroundColor: COLORS.WHITE,
    right: 0,
    top: 0,
  },
  chatContainer: {
    flex: 1,
  },
  // inputToolbarContainer: {
  //   backgroundColor: COLORS.WHITE,
  //   borderTopWidth: 1,
  //   borderTopColor: COLORS.GREYSCALE_200,
  //   paddingHorizontal: SCREEN_PADDING,
  //   paddingVertical: 8,
  //   paddingBottom: 8,
  //   height: 200,
  // },
  inputToolbarPrimary: {
    alignItems: 'center',
  },
  textInput: {
    backgroundColor: COLORS.GREYSCALE_50,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    fontFamily: 'Manrope-Regular',
    color: COLORS.GREYSCALE_900,
    borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    marginRight: 8,
    maxHeight: 100,
  },
  textInputInner: {
    fontSize: 14,
    fontFamily: 'Manrope-Regular',
    color: COLORS.GREYSCALE_900,
  },
  attachmentButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  sendContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 0,
    marginBottom: 0,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: COLORS.PRIMARY_400,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  sendButtonDisabled: {
    backgroundColor: COLORS.GREYSCALE_200,
    opacity: 0.5,
  },
  dayWrapper: {
    marginBottom: 12,
    marginTop: 8,
    backgroundColor: COLORS.WHITE,
  },
  dayText: {
    fontSize: 12,
    fontFamily: FONTS.regular,
    color: COLORS.PRIMARY_300,
  },
  inputToolbarContainer: {
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingHorizontal: 16,
    paddingVertical: 20,
    backgroundColor: COLORS.WHITE,
    height: 150,
  },
  inputToolbarRow: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    // height: 55,
  },
  composerInput: {},
  composerWrapper: {
    flex: 1,
    position: 'relative',
    marginRight: 12,
  },
  attachmentIconButton: {
    position: 'absolute',
    right: 12,
    top: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  contractsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.GREYSCALE_50,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    // borderWidth: 1,
    borderColor: COLORS.GREYSCALE_200,
    width: SCREEN.WIDTH - 150,
  },
  contractIconContainer: {
    position: 'relative',
    marginRight: 12,
  },
  contractBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.RED_NOTIFICATION,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.WHITE,
  },
  contractNamesContainer: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  contractName: {
    lineHeight: 18,
  },
  contractMessageContainer: {
    // borderRadius: 12,
    padding: 12,
    marginBottom: 4,
    maxWidth: '80%',
  },
  contractMessageRight: {
    alignSelf: 'flex-end',
    marginRight: 4,
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 0,
  },
  contractMessageLeft: {
    alignSelf: 'flex-start',
    marginLeft: 4,
    backgroundColor: COLORS.WHITE,
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 0,
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
  },
  contractFileItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.PRIMARY_30,
    borderRadius: 8,
    padding: 10,
    marginBottom: 8,
  },
  contractFileItemLast: {
    marginBottom: 0,
  },
  contractFileName: {
    marginLeft: 12,
    flex: 1,
    color: COLORS.PRIMARY,
    marginTop: 8,
  },
});

export default styles;
